export type Product = {
  slug: string;
  name: string;
  category: string;
  image: string;
  shortDescription: string;
  description: string;
  vehicles: string[];
  availability: string;
};

const starterProducts: Product[] = [
  {
    slug: "hydraulic-filter",
    name: "Hydraulic Filter",
    category: "Filters",
    image: "/1.jpg",
    shortDescription: "Reliable filtration for hydraulic systems and heavy machinery uptime.",
    description:
      "Designed for demanding construction and agricultural environments, this hydraulic filter helps protect pumps, valves, and cylinders from contamination while maintaining steady operating pressure.",
    vehicles: ["Caterpillar 320D", "Komatsu WA380", "John Deere 6M"],
    availability: "In Stock",
  },
  {
    slug: "service-kit",
    name: "Service Kit",
    category: "Service Kits",
    image: "/2.jpg",
    shortDescription: "Complete maintenance kit for routine service and long-term durability.",
    description:
      "A full-service maintenance package tailored for trucks and machinery that require regular inspection, lubrication, and replacement of wear items to stay reliable on site.",
    vehicles: ["Volvo FM", "Isuzu FVR", "Hino 500"],
    availability: "Contact Us for Availability",
  },
  {
    slug: "engine-oil",
    name: "Engine Oil",
    category: "Lubricants",
    image: "/3.jpg",
    shortDescription: "Premium engine lubricant for high-temperature performance and protection.",
    description:
      "This premium engine oil offers strong temperature stability and excellent wear protection for diesel engines operating in tough workloads and long duty cycles.",
    vehicles: ["Scania P-series", "Mercedes-Benz Actros", "DAF XF"],
    availability: "In Stock",
  },
  {
    slug: "air-dryer",
    name: "Air Dryer",
    category: "Air Systems",
    image: "/4.jpg",
    shortDescription: "Essential air system component for moisture control and brake efficiency.",
    description:
      "Built to keep compressed air systems dry and dependable, this air dryer supports brake performance and helps prevent corrosion in critical air lines and valves.",
    vehicles: ["MAN TGS", "Kenworth T680", "Toyota Dyna"],
    availability: "In Stock",
  },
];

export const pictureProducts: Product[] = [
  {
    slug: "transmission-components-clutch",
    name: "Clutch",
    category: "Transmission Components",
    image: "/clutch.jpg",
    shortDescription: "Clutch assembly for smooth power transfer and dependable engagement.",
    description: "A durable clutch component for heavy-duty drivetrains and frequent stop-start operations.",
    vehicles: ["Komatsu", "Caterpillar", "Volvo"],
    availability: "In Stock",
  },
  {
    slug: "transmission-components-syncronisers",
    name: "Syncronisers",
    category: "Transmission Components",
    image: "/syncronisers.jpg",
    shortDescription: "Precision synchronizers for smoother gear shifting.",
    description: "High-quality synchronizer parts that help improve gear engagement and reduce wear in transmission systems.",
    vehicles: ["MAN", "Scania", "DAF"],
    availability: "In Stock",
  },
  {
    slug: "transmission-components-flywheel",
    name: "Flywheel",
    category: "Transmission Components",
    image: "/flywheel.jpeg",
    shortDescription: "Robust flywheel for stable torque transfer and clutch operation.",
    description: "Built to endure heavy-duty engine torque and support long-lasting clutch performance.",
    vehicles: ["John Deere", "Caterpillar", "Case"],
    availability: "In Stock",
  },
  {
    slug: "transmission-components-gearsets",
    name: "Gearsets",
    category: "Transmission Components",
    image: "/gearsets.jpg",
    shortDescription: "Gearset assemblies for dependable power delivery.",
    description: "Precision gearsets designed to keep transmissions operating smoothly under load.",
    vehicles: ["Komatsu", "Volvo", "Kenworth"],
    availability: "In Stock",
  },
  {
    slug: "engine-components-cylinder-head",
    name: "Cylinder Head",
    category: "Engine Components",
    image: "/cylinder head.jpg",
    shortDescription: "Engine cylinder head for efficient combustion and sealing.",
    description: "Reliable cylinder head components that help maintain compression and engine performance.",
    vehicles: ["Caterpillar", "Cummins", "Isuzu"],
    availability: "In Stock",
  },
  {
    slug: "engine-components-cylinder-block",
    name: "Cylinder Block",
    category: "Engine Components",
    image: "/Cylinder-Block.jpg",
    shortDescription: "Heavy-duty block for strong engine structure and durability.",
    description: "A robust engine block suitable for demanding industrial and transport applications.",
    vehicles: ["Komatsu", "Scania", "Hino"],
    availability: "In Stock",
  },
  {
    slug: "engine-components-camshaft",
    name: "Camshaft",
    category: "Engine Components",
    image: "/camshaft.webp",
    shortDescription: "Camshaft for precise valve timing and engine efficiency.",
    description: "Engineered to support smooth valve operation and dependable top-end performance.",
    vehicles: ["MAN", "DAF", "Mercedes"],
    availability: "In Stock",
  },
  {
    slug: "engine-components-crankshaft",
    name: "Crankshaft",
    category: "Engine Components",
    image: "/crankshaft.jpg",
    shortDescription: "Crankshaft for balanced engine rotation and strength.",
    description: "Designed to handle high torque loads with minimal vibration and long service life.",
    vehicles: ["Volvo", "Caterpillar", "John Deere"],
    availability: "In Stock",
  },
  {
    slug: "engine-components-pistons",
    name: "Pistons",
    category: "Engine Components",
    image: "/pistons.jpg",
    shortDescription: "Pistons suited for efficient combustion and wear resistance.",
    description: "High-performance piston components that support good fuel economy and durability.",
    vehicles: ["Komatsu", "Caterpillar", "Scania"],
    availability: "In Stock",
  },
  {
    slug: "engine-components-connecting-rods",
    name: "Connecting Rods",
    category: "Engine Components",
    image: "/connecting rods.jpg",
    shortDescription: "Connecting rods for dependable engine reciprocation.",
    description: "Strong connecting rod assemblies built to withstand repetitive engine loading.",
    vehicles: ["Hino", "Isuzu", "Volvo"],
    availability: "In Stock",
  },
  {
    slug: "service-kits",
    name: "Service Kits",
    category: "Service Kits",
    image: "/service kits.jpg",
    shortDescription: "Complete maintenance kits for scheduled servicing.",
    description: "A practical service kit bundle to keep equipment running reliably between major overhauls.",
    vehicles: ["Komatsu", "John Deere", "Caterpillar"],
    availability: "In Stock",
  },
  {
    slug: "sdlg",
    name: "SDLG",
    category: "SDLG",
    image: "/SDLG.webp",
    shortDescription: "SDLG parts support for construction machinery uptime.",
    description: "Replacement parts and components suited for SDLG equipment fleets.",
    vehicles: ["SDLG", "Construction", "Mining"],
    availability: "In Stock",
  },
  {
    slug: "sany",
    name: "SANY",
    category: "SANY",
    image: "/SANY.webp",
    shortDescription: "SANY-compatible parts for dependable machine support.",
    description: "Reliable replacement parts for SANY excavators and earthmoving machines.",
    vehicles: ["SANY", "Mining", "Roadworks"],
    availability: "In Stock",
  },
  {
    slug: "suspension",
    name: "Suspension",
    category: "Suspension",
    image: "/suspension.webp",
    shortDescription: "Suspension components for comfort and stability.",
    description: "Robust suspension parts designed to protect the machine and improve ride quality.",
    vehicles: ["Volvo", "Scania", "Mercedes"],
    availability: "In Stock",
  },
  {
    slug: "ripper-tips",
    name: "Ripper Tips",
    category: "Ripper Tips",
    image: "/ripper tips.jpg",
    shortDescription: "Durable ripper tips for earthmoving and trenching.",
    description: "Hard-wearing tips that stand up to abrasive ground conditions and heavy digging.",
    vehicles: ["Caterpillar", "Komatsu", "Doosan"],
    availability: "In Stock",
  },
  {
    slug: "air-dryer-part",
    name: "Air Dryer",
    category: "Air Dryer",
    image: "/air dryer.jpg",
    shortDescription: "Air dryer for moisture control and brake efficiency.",
    description: "Supports dry compressed air systems and helps protect critical brake and pneumatic components.",
    vehicles: ["MAN", "Kenworth", "Toyota"],
    availability: "In Stock",
  },
  {
    slug: "air-filter",
    name: "Air Filter",
    category: "Air Filter",
    image: "/air filter.jpg",
    shortDescription: "Efficient air filtration for clean intake performance.",
    description: "Helps protect engines from dust and contamination in harsh working environments.",
    vehicles: ["John Deere", "Komatsu", "Volvo"],
    availability: "In Stock",
  },
  {
    slug: "fuel-filter",
    name: "Fuel Filter",
    category: "Fuel Filters",
    image: "/fuel filter.jpg",
    shortDescription: "Fuel filter for clean diesel delivery and engine protection.",
    description: "Reliable fuel filtration designed to prevent contaminants from reaching injectors and the engine.",
    vehicles: ["Caterpillar", "Scania", "Isuzu"],
    availability: "In Stock",
  },
  {
    slug: "engine-oil-part",
    name: "Engine Oil",
    category: "Engine Oil",
    image: "/engine oil.jpg",
    shortDescription: "Premium engine lubricant for high-temperature duty cycles.",
    description: "A trusted lubricant option for heavy-duty diesel engines and long operating hours.",
    vehicles: ["DAF", "Mercedes", "MAN"],
    availability: "In Stock",
  },
  {
    slug: "motor-adapters",
    name: "Motor Adapters",
    category: "Adapters",
    image: "/motor_adapters.jpg",
    shortDescription: "Adapter fittings for flexible equipment connections.",
    description: "Versatile adapter parts that help connect systems and components with ease.",
    vehicles: ["Construction", "Agriculture", "Transport"],
    availability: "In Stock",
  },
  {
    slug: "transmission-filters",
    name: "Transmission Filters",
    category: "Transmission Filters",
    image: "/transmission filters.jpg",
    shortDescription: "Transmission filters for cleaner flow and better protection.",
    description: "Protects transmission systems from contamination and supports smooth operation.",
    vehicles: ["Volvo", "Scania", "DAF"],
    availability: "In Stock",
  },
  {
    slug: "grader-blades",
    name: "Grader Blades",
    category: "Grader Blades",
    image: "/Grader-Blades-5.jpg",
    shortDescription: "Grader blades for effective road and site maintenance.",
    description: "Durable grader blade parts designed for consistent earthmoving and grading performance.",
    vehicles: ["Caterpillar", "Komatsu", "John Deere"],
    availability: "In Stock",
  },
  {
    slug: "komatsu",
    name: "Komatsu",
    category: "Komatsu",
    image: "/komatsu.jpg",
    shortDescription: "Komatsu-compatible parts and components.",
    description: "Quality replacement parts suitable for Komatsu heavy machinery applications.",
    vehicles: ["Komatsu", "Excavators", "Dozers"],
    availability: "In Stock",
  },
  {
    slug: "multipurpose-grease",
    name: "Multipurpose Grease",
    category: "Multipurpose Grease",
    image: "/multipurpose greese.jpg",
    shortDescription: "General-purpose grease for heavy-duty lubrication needs.",
    description: "A dependable grease solution for joints, pins, bearings, and other wear points.",
    vehicles: ["Agriculture", "Mining", "Transport"],
    availability: "In Stock",
  },
  {
    slug: "multipurpose-grease-1",
    name: "Multipurpose Grease 1",
    category: "Multipurpose Grease",
    image: "/multipurpose greese1.jpg",
    shortDescription: "Additional grease option for varied maintenance applications.",
    description: "Suitable for general lubrication tasks that require a flexible, heavy-duty grease product.",
    vehicles: ["Construction", "Agriculture", "Mining"],
    availability: "In Stock",
  },
  {
    slug: "compressor-oil",
    name: "Compressor Oil",
    category: "Compressor Oil",
    image: "/compressor oil.jpg",
    shortDescription: "Compressor oil for steady lubrication and cooling.",
    description: "Helps protect compressor systems and maintain dependable air output under load.",
    vehicles: ["Compressors", "Workshops", "Transport"],
    availability: "In Stock",
  },
  {
    slug: "hydraulic-oil-46",
    name: "Hydraulic Oil 46",
    category: "Hydraulic Oil 46",
    image: "/hydraulic oil 46.webp",
    shortDescription: "Hydraulic oil 46 for smooth hydraulic system performance.",
    description: "Designed for hydraulic systems that require dependable viscosity control and wear protection.",
    vehicles: ["Excavators", "Loaders", "Cranes"],
    availability: "In Stock",
  },
  {
    slug: "hydraulic-oil-68",
    name: "Hydraulic Oil 68",
    category: "Hydraulic Oil 68",
    image: "/hydraulic oil 68.jpg",
    shortDescription: "Hydraulic oil 68 for heavier-duty hydraulic circulation.",
    description: "Supports higher-load hydraulic systems with stable performance in demanding conditions.",
    vehicles: ["Dozers", "Excavators", "Tractors"],
    availability: "In Stock",
  },
  {
    slug: "john-deere",
    name: "John Deere",
    category: "John Deere",
    image: "/JohnDeere.webp",
    shortDescription: "John Deere-compatible parts for dependable operation.",
    description: "Replacement parts tailored for John Deere machinery and maintenance routines.",
    vehicles: ["John Deere", "Agriculture", "Forestry"],
    availability: "In Stock",
  },
  {
    slug: "hydraulic-filters",
    name: "Hydraulic Filters",
    category: "Hydraulic Filters",
    image: "/hydraulic filters.jpg",
    shortDescription: "Hydraulic filters for cleanliness and uptime.",
    description: "Keeps hydraulic systems free of damaging particles and supports stable pressure control.",
    vehicles: ["Caterpillar", "Komatsu", "John Deere"],
    availability: "In Stock",
  },
  {
    slug: "caterpillar",
    name: "Caterpillar",
    category: "Caterpillar",
    image: "/caterpillarr.jpg",
    shortDescription: "Caterpillar-compatible parts for heavy-duty use.",
    description: "Parts and components designed to support Caterpillar machines in tough environments.",
    vehicles: ["Caterpillar", "Construction", "Mining"],
    availability: "In Stock",
  },
  {
    slug: "oil-filters",
    name: "Oil Filters",
    category: "Oil Filters",
    image: "/oil filters.png",
    shortDescription: "Oil filters to protect engines from debris and wear.",
    description: "Reliable engine oil filtration for cleaner operation and extended maintenance intervals.",
    vehicles: ["Scania", "Volvo", "MAN"],
    availability: "In Stock",
  },
  {
    slug: "oil-air-separator-filters",
    name: "Oil Air Separator Filters",
    category: "Oil Air Separator Filters",
    image: "/oilair separater filter.jpg",
    shortDescription: "Separator filters for air and oil system efficiency.",
    description: "Helps keep compressed air systems clean and improves the performance of oil separation equipment.",
    vehicles: ["Transport", "Workshops", "Compressors"],
    availability: "In Stock",
  },
];

export const products: Product[] = [...starterProducts, ...pictureProducts];

export const featuredProducts = products.slice(0, 4);
